### ISSUE TITLE
Incomplete CRC cards and Data Dictionary

### ISSUE THREAD

**Issue by ChrisWasTakenwastaken** [CS-3321/LearningPlatform#12]
Preview:
[Data Dictionary.docx](https://github.com/CS-3321/LearningPlatform/files/2442758/Data.Dictionary.docx)

I'm relying on comments to supply the details of CRC cards, so I'll focus on the best documented classes first.
Let me know if a given class was taken wholesale from the internet.

I'm not certain I'm building this properly; I'll need to read the relevant sections of chapter 13 before I progress.

Also, I'm not certain I'll ever finish the data dictionary. I'll work on it during weeks when Dr. Chang doesn't introduce some other sort of design artifact.

**Comment by NoteMEdown** [comment]
The only thing I didn't write was the theme. Nothing else was taken from the internet.

**Comment by ChrisWasTakenwastaken** [comment]
Thanks.
