### ISSUE TITLE
Create Students

### ISSUE THREAD

**Issue by NoteMEdown** [CS-3321/LearningPlatform#4]
Teacher must be able to create students by adding them to classes.
The Teacher must be asked for the students first and last name, as well as their student ID,
The password could be decided by the teacher, or find a way for the student to decide.
Maybe assign a temporary password to the student, which they have to change during their first login (and only their first login)

**Comment by ChrisWasTakenwastaken** [comment]
Users are just stored sequentially in the text file, right? 
Updating their information will be dificult in that the case.


Also, I changed a few words in the AddTeacher function from the Database class:

public static bool AddStudent(string _user, string _pass, string _fName, string _lName)
        {
            string fileName = String.Format(@"{0}\UserLogins.txt", Application.StartupPath);
            if (users.ContainsKey(_user)) // If the that username is already registered, let the user know
                return false;
            // Otherwise register the student
            User newUser = new User(_user, _pass, _fName, _lName, "", false); // Creates a student with no classes
            users.Add(_user, newUser); // Adds the student to the List of users
            // Now Store in file
            File.AppendAllText(fileName, newUser.Encoded()+"|");
            return true;
        }

**Comment by NoteMEdown** [comment]
If you wanted to update the fourth users info, just read all users into a list, change the one you need change, then clear all info in the text file, and add all the users again,
Or you could do what I came up with for the classes, store all the students usernames/ids in one text file (Since username never changes) then make a new text file for every user with the filename being their username.
I decided we should do that with classes since they update a lot, and I dont want to have to resave every class when updating one of them.


________________________________
