### ISSUE TITLE
Read in every SchoolClass

### ISSUE THREAD

**Issue by NoteMEdown** [CS-3321/LearningPlatform#7]
Where to complete this task: Database.cs

Remove comment "// TODO: Read in all class files based on class names in the classNames List, store them in the classes Dictionary" 

In its location, Read in all SchoolClass's info and create a SchoolClass (Pass the info to the constructor)
add all these SchoolClass' to the classes Dictionary. (See how I did this for Users as an example)

**Comment by ChrisWasTakenwastaken** [comment]
Why not just repeat the steps you used for creating users?

SchoolClass _tempClass = null; // Blank temp class
                 foreach (string _classInfo in _allClasses) { 
                      _tempClass = new SchoolClass(_classInfo); // Create the new SchoolClass
                      classes.Add(_tempClass.classID, _tempClass); // Add the class to the Dictionary
                  }

**Comment by NoteMEdown** [comment]
It will be similar, however, the array _allClasses won't exist.
Unlike users (which are all stores in a single string in a single file)
SchoolClass's are all stored in their own file, thus separate strings.

the foreach loop would have to read read the _classInfo from the file.
