### ISSUE TITLE
Preliminary Use Case Document

### ISSUE THREAD

**Issue by ChrisWasTakenwastaken** [CS-3321/LearningPlatform#9]
[Use Cases.docx](https://github.com/CS-3321/LearningPlatform/files/2416457/Use.Cases.docx)
Please review.

**Comment by ChrisWasTakenwastaken** [comment]
![cs 1](https://user-images.githubusercontent.com/42503183/46119119-3ec09680-c1cf-11e8-99ea-35f475f1d348.png)

**Comment by NoteMEdown** [comment]
For the picture, Both types of users can also view grades, Teacher can also modify grades.
For the use case, to add a student to class, the actions just need to be specify class ID and student ID.

**Comment by ChrisWasTakenwastaken** [comment]
![cs 1](https://user-images.githubusercontent.com/42503183/46164049-89372700-c252-11e8-8383-e630258814c7.png)

**Comment by ChrisWasTakenwastaken** [comment]
[Use.Cases.docx](https://github.com/CS-3321/LearningPlatform/files/2429202/Use.Cases.docx)
